"""empty message

Revision ID: 182eebf1c6f3
Revises: d9c925ae877d
Create Date: 2020-12-23 17:22:31.501387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182eebf1c6f3'
down_revision = 'd9c925ae877d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_ids', sa.Integer(), nullable=True))
    op.drop_constraint('show_venue_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'Venue', ['venue_ids'], ['id'])
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_venue_id_fkey', 'show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('show', 'venue_ids')
    # ### end Alembic commands ###
