"""empty message

Revision ID: f91ae2eb2d52
Revises: 182eebf1c6f3
Create Date: 2020-12-23 17:22:50.558100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91ae2eb2d52'
down_revision = '182eebf1c6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('show_venue_ids_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'Venue', ['venue_id'], ['id'])
    op.drop_column('show', 'venue_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_venue_ids_fkey', 'show', 'Venue', ['venue_ids'], ['id'])
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###
